# y dataset pipeline

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))

from data_loaders import Training_set
import pandas as pd
import numpy as np

In [5]:
ts = Training_set()
x_train, y_train, _, _= ts.split_small_data()
y_train.head()

,run_no,total_calculation_time,result_committed_hogga_g1_t0,result_committed_hogga_g1_t1,result_committed_hogga_g1_t2,result_committed_hogga_g1_t3,result_committed_hogga_g1_t4,result_committed_hogga_g1_t5,result_committed_hogga_g1_t6,result_committed_hogga_g1_t7,...,result_committed_vesle_kjela_g1_t158,result_committed_vesle_kjela_g1_t159,result_committed_vesle_kjela_g1_t160,result_committed_vesle_kjela_g1_t161,result_committed_vesle_kjela_g1_t162,result_committed_vesle_kjela_g1_t163,result_committed_vesle_kjela_g1_t164,result_committed_vesle_kjela_g1_t165,result_committed_vesle_kjela_g1_t166,result_committed_vesle_kjela_g1_t167
starttime,,,,,,,,,,,,,,,,,,,,,
2015-01-01 00:00:00+00:00,1,48.950692,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-02 00:00:00+00:00,2,56.048899,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-03 00:00:00+00:00,3,44.280307,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-04 00:00:00+00:00,4,40.848453,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-05 00:00:00+00:00,5,44.036279,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [7]:
x_train.head()

,day_ahead_price,langesae_inflow,staavatn_inflow,kjelavatn_inflow,bordalsvatn_inflow,foersvatn_inflow,hyljelihyl_inflow,venemo_inflow,bitdalsvatn_inflow,songavatn_inflow,...,vaamarvatn_wv,langeidvatn_wv,totak_wv,songavatn_wv,vinjevatn_wv,bandak_wv,bordalsvatn_wv,byrtevatn_wv,hyljelihyl_wv,vatjern_wv
date,,,,,,,,,,,,,,,,,,,,,
2015-01-01 00:00:00+00:00,27.07,0.63,0.81,1.06,0.90,0.09,0.61,0.57,1.83,8.42,...,28.98,4.78,28.98,30.13,22.65,7.73,31.81,9.32,28.98,4.78
2015-01-01 01:00:00+00:00,26.93,0.63,0.82,1.06,0.89,0.09,0.60,0.59,1.81,8.35,...,28.98,4.78,28.98,30.13,22.65,7.73,31.81,9.32,28.98,4.78
2015-01-01 02:00:00+00:00,26.83,0.62,0.82,1.06,0.90,0.09,0.61,0.59,1.79,8.25,...,28.98,4.78,28.98,30.13,22.65,7.73,31.81,9.32,28.98,4.78
2015-01-01 03:00:00+00:00,26.81,0.62,0.81,1.06,0.89,0.09,0.60,0.59,1.79,8.25,...,28.98,4.78,28.98,30.13,22.65,7.73,31.81,9.32,28.98,4.78
2015-01-01 04:00:00+00:00,26.97,0.62,0.81,1.05,0.88,0.09,0.60,0.59,1.78,8.20,...,28.98,4.78,28.98,30.13,22.65,7.73,31.81,9.32,28.98,4.78