# y dataset pipeline

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))

from data_loaders import Training_set
import pandas as pd
import numpy as np

In [2]:
ts = Training_set()
x_train, y_train, _, _= ts.split_small_data()
y_train.head()

,result_committed_hogga_g1_t0,result_committed_hogga_g1_t1,result_committed_hogga_g1_t2,result_committed_hogga_g1_t3,result_committed_hogga_g1_t4,result_committed_hogga_g1_t5,result_committed_hogga_g1_t6,result_committed_hogga_g1_t7,result_committed_hogga_g1_t8,result_committed_hogga_g1_t9,...,result_committed_vesle_kjela_g1_t158,result_committed_vesle_kjela_g1_t159,result_committed_vesle_kjela_g1_t160,result_committed_vesle_kjela_g1_t161,result_committed_vesle_kjela_g1_t162,result_committed_vesle_kjela_g1_t163,result_committed_vesle_kjela_g1_t164,result_committed_vesle_kjela_g1_t165,result_committed_vesle_kjela_g1_t166,result_committed_vesle_kjela_g1_t167
starttime,,,,,,,,,,,,,,,,,,,,,
2015-01-01 00:00:00+00:00,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-02 00:00:00+00:00,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-03 00:00:00+00:00,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-04 00:00:00+00:00,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2015-01-05 00:00:00+00:00,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [3]:
x_train.head()

,day_ahead_price_t0,day_ahead_price_t1,day_ahead_price_t2,day_ahead_price_t3,day_ahead_price_t4,day_ahead_price_t5,day_ahead_price_t6,day_ahead_price_t7,day_ahead_price_t8,day_ahead_price_t9,...,vaamarvatn_wv,langeidvatn_wv,totak_wv,songavatn_wv,vinjevatn_wv,bandak_wv,bordalsvatn_wv,byrtevatn_wv,hyljelihyl_wv,vatjern_wv
starttime,,,,,,,,,,,,,,,,,,,,,
2015-01-01 00:00:00+00:00,27.070000,26.930000,26.830000,26.809999,26.969999,27.070000,26.799999,26.969999,26.980000,27.059999,...,28.980000,4.78,28.980000,30.129999,22.650000,7.73,31.809999,9.32,28.980000,4.78
2015-01-02 00:00:00+00:00,26.410000,26.200001,25.600000,24.740000,26.100000,27.250000,28.370001,28.370001,28.320000,28.299999,...,26.440001,4.44,26.440001,30.520000,35.130001,8.52,30.959999,8.72,26.440001,4.44
2015-01-03 00:00:00+00:00,25.540001,25.430000,25.340000,25.290001,25.299999,25.549999,26.750000,26.980000,27.520000,27.719999,...,26.360001,4.28,26.360001,30.389999,35.299999,10.18,30.510000,8.43,26.360001,4.28
2015-01-04 00:00:00+00:00,27.379999,27.170000,27.030001,27.040001,27.190001,27.129999,27.059999,27.629999,28.030001,28.240000,...,26.330000,4.23,26.330000,30.110001,28.629999,7.16,30.059999,7.96,26.330000,4.23
2015-01-05 00:00:00+00:00,28.150000,28.129999,28.049999,28.040001,28.459999,28.780001,30.990000,38.150002,41.509998,40.459999,...,26.059999,3.89,26.059999,29.580000,31.330000,3.14,29.350000,7.40,26.059999,3.89